I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 41, in script call
    call wake_up
  File "game/script.rpy", line 54, in script call
    call wu_day
  File "game/script.rpy", line 41, in script call
    call wake_up
  File "game/script.rpy", line 54, in script call
    call wu_day
ScriptError: could not find label 'wu_day'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 41, in script call
    call wake_up
  File "game/script.rpy", line 54, in script call
    call wu_day
  File "C:\Users\Russel\Downloads\renpy-8.3.3-sdk\renpy\ast.py", line 1414, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 41, in script call
    call wake_up
  File "game/script.rpy", line 54, in script call
    call wu_day
  File "C:\Users\Russel\Downloads\renpy-8.3.3-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'wu_day'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.3.24111502
Wumauhen 1.0
Tue Nov 19 13:35:36 2024
